name: discount_now
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  either_dart: ^0.1.4
  equatable: ^2.0.3
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  get_storage: ^2.0.3
  firebase_storage: ^10.3.1
  firebase_auth: ^3.4.1
  sticky_headers: ^0.3.0+2
  card_swiper: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1
  pin_code_fields: ^7.4.0
  maps_launcher: ^2.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

  flutter_gen_runner:

flutter:
  assets:
    - assets/images/

  uses-material-design: true

flutter_gen: 
  output: lib/app/gen/
  integrations: 
    flutter_svg: true

