// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYVTU2hftASGqHxxivWBLR6qNcqe_9oI',
    appId: '1:856314222153:web:ad14361334507531a55198',
    messagingSenderId: '856314222153',
    projectId: 'discount-now-now',
    authDomain: 'discount-now-now.firebaseapp.com',
    storageBucket: 'discount-now-now.appspot.com',
    measurementId: 'G-EY45X0YR45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgX9_pcuftf7IBMCmCi8yfMR3nbkONUhE',
    appId: '1:856314222153:android:8a25ec0ca344e02ba55198',
    messagingSenderId: '856314222153',
    projectId: 'discount-now-now',
    storageBucket: 'discount-now-now.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrB9fBXW7EyfKEAWU7U4xtsAVWT0ftQoc',
    appId: '1:856314222153:ios:8fb0413379c6fd1ba55198',
    messagingSenderId: '856314222153',
    projectId: 'discount-now-now',
    storageBucket: 'discount-now-now.appspot.com',
    iosClientId: '856314222153-b3in6q7gu25cd77mfke3khk6ul22ej9h.apps.googleusercontent.com',
    iosBundleId: 'com.treetechies.discountNow',
  );
}
